# Generated by Django 4.2.28 on 2026-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='competition_pics/'),
        ),
    ]
