# Generated by Django 4.2.28 on 2026-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
