# Generated by Django 4.2.28 on 2026-03-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ad'),
        ('api', '0004_competition_picture'),
    ]

    operations = [
    ]
