# Generated by Django 4.2.28 on 2026-03-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dog_picture'),
        ('api', '0005_merge_0004_ad_0004_competition_picture'),
    ]

    operations = [
    ]
