# Generated by Django 4.2.29 on 2026-03-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_participant"),
        ("api", "0006_merge_20260303_1433"),
    ]

    operations = []
