# Generated by Django 4.2.29 on 2026-03-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_merge_0004_participant_0006_merge_20260303_1433"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="participant", unique_together=set(),),
        migrations.AddField(
            model_name="participant",
            name="dog",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.dog"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participant", unique_together={("competition", "user", "dog")},
        ),
        migrations.RemoveField(model_name="participant", name="dog_identifier",),
    ]
