# Generated by Django 4.2.28 on 2026-03-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_like'),
        ('api', '0010_alter_comment_text'),
    ]

    operations = [
    ]
