# Generated by Django 4.2.28 on 2026-03-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_0009_like_0010_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.participant'),
        ),
    ]
